"""
NexaVigil - Remediation Reporter
Generates structured reports and sends to Slack.
NEVER automatic — only after officer approval.
"""
import os
import json
import logging
from typing import Dict
from datetime import datetime
import requests
from dotenv import load_dotenv
load_dotenv()

logger = logging.getLogger("remediation_reporter")

SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")


def generate_report(case: Dict) -> str:
    """
    Generate structured Markdown report from approved case.
    Includes uncertainty caveats — never definitive.
    """
    report = f"""# Confluence Compliance Report

**Case ID:** {case['case_id']}  
**Generated:** {datetime.now().isoformat()}  
**Status:** OFFICER APPROVED  
**Officer:** {case.get('officer_id', 'Maria Chen')}

---

## Executive Summary

A cross-market anomaly was detected requiring human review. This report presents temporal correlations only — no causation is implied.

## Detected Events

### Prediction Market Anomaly
- **Fixture:** {case['odds_event_ref']}
- **Convergence Score:** {case['convergence_score']}/100
- **Confidence:** {case['confidence']}

### Equity Signal
- **Ticker:** {case['equity_signal_ref']}
- **Skeptic Score:** {case['skeptic_score']}/100 (lower = more suspicious)

## Reasoning Chain
"""
    for i, reason in enumerate(case.get('reasoning_chain', []), 1):
        report += f"{i}. {reason}\n"

    report += "\n## Evidence\n"
    for i, evidence in enumerate(case.get('evidence_list', []), 1):
        report += f"{i}. {evidence}\n"

    report += f"""
## Skeptic Review
**Score:** {case['skeptic_score']}/100  
**Alternative Explanations Checked:**
"""
    for explanation in case.get('alternative_explanations', []):
        report += f"- {explanation}\n"

    report += """
---

## Uncertainty Caveats

1. This system detects **temporal correlations only**, not causation.
2. All findings require human review before any action.
3. Benign explanations may exist that were not identified.
4. This report was generated by an AI system and must be verified.

## Recommended Action

**{recommended_action}**

---
*Generated by NexaVigil | All Things Agentic Hackathon*
""".format(recommended_action=case.get('recommended_action', 'requires human review'))

    return report


def send_to_slack(report: str, case_id: str) -> bool:
    """Send report to Slack webhook."""
    if not SLACK_WEBHOOK_URL:
        logger.warning("No SLACK_WEBHOOK_URL configured, skipping Slack send")
        return False

    payload = {
        "text": f"🚨 Confluence Alert — Case {case_id} Approved",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"Confluence Report: {case_id}",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"Officer *{case_id}* has approved a cross-market anomaly case.\n\n*Convergence Score:* High\n*Skeptic Score:* Low (no benign explanation found)"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"```{report[:2900]}```"  # Slack limit
                }
            }
        ]
    }

    try:
        response = requests.post(
            SLACK_WEBHOOK_URL,
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=10,
        )
        response.raise_for_status()
        logger.info(f"Slack notification sent for case {case_id}")
        return True
    except Exception as e:
        logger.error(f"Failed to send Slack notification: {e}")
        return False


def process_approved_case(case: Dict) -> Dict:
    """
    Full flow: generate report + send to Slack.
    Called ONLY when officer approves a case.
    """
    report = generate_report(case)
    
    # Save report to case
    case['report'] = report
    case['report_generated_at'] = datetime.now().isoformat()

    # Send to Slack
    slack_sent = send_to_slack(report, case['case_id'])

    return {
        "case_id": case['case_id'],
        "report_generated": True,
        "slack_sent": slack_sent,
        "report_length": len(report),
    }


if __name__ == "__main__":
    # Test with approved case
    test_case = {
        "case_id": "test-case-001",
        "odds_event_ref": "nfl-wk1-kc-buf-2026",
        "equity_signal_ref": "DKNG",
        "convergence_score": 75,
        "skeptic_score": 20,
        "reasoning_chain": [
            "Sharp 12.6% move on Kalshi NFL market",
            "DKNG CEO purchased $125K same day",
            "14.5 hour temporal proximity",
            "Both reference same entity (DraftKings ecosystem)"
        ],
        "evidence_list": [
            "Kalshi odds: 45 -> 62 (+37.8%)",
            "Jason Robins Form 4: $125K purchase"
        ],
        "confidence": "medium",
        "recommended_action": "requires human review",
        "alternative_explanations": [
            "Possible 10b5-1 trading plan",
            "General market sentiment shift"
        ],
        "officer_id": "maria",
        "status": "approve",
    }

    result = process_approved_case(test_case)
    print(json.dumps(result, indent=2))
    print("\n--- REPORT ---\n")
    print(test_case['report'])